# Generated by Django 4.2.1 on 2023-05-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0002_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='category',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
