# Generated by Django 4.2.1 on 2023-06-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0004_testresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
