# Generated by Django 4.1.7 on 2023-04-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_patientregister_remove_patient_user_delete_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientregister',
            table='PatientRegister',
        ),
    ]
