# Generated by Django 4.1.7 on 2023-04-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_patientregister_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientregister',
            table='patientregister',
        ),
    ]
