# Generated by Django 4.1.7 on 2023-04-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_patientregister_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregister',
            name='id',
        ),
        migrations.AlterField(
            model_name='patientregister',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
