# Generated by Django 4.2.1 on 2023-05-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_patientregister_confirm_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patientregister',
        ),
    ]
