# Generated by Django 4.2.1 on 2023-06-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminView', '0005_delete_testresult'),
        ('patient', '0032_alter_diagnosticorder_payment_status'),
        ('Home', '0007_delete_patientregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.diagnosticorder')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminView.diagnostic')),
            ],
        ),
    ]
