# Generated by Django 4.2.1 on 2023-06-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0032_alter_diagnosticorder_payment_status'),
        ('Home', '0009_testresult_normal_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('patient_weight', models.FloatField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('patient_blood_pressure', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=254)),
                ('doctor_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=9)),
                ('frequency', models.CharField(max_length=10)),
                ('eat_time', models.CharField(choices=[('Before Eat', 'Before Eat'), ('After Eat', 'After Eat')], max_length=10)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.prescription')),
            ],
        ),
    ]
