# Generated by Django 4.2.1 on 2023-06-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0032_alter_diagnosticorder_payment_status'),
        ('Home', '0010_prescription_test_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='eat_time',
            field=models.CharField(choices=[('Before Eat', 'Before Eat'), ('After Eat', 'After Eat')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='patient.appointment'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
