# Generated by Django 4.2.1 on 2023-06-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_medicine_dosage_alter_medicine_eat_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='prescription',
        ),
        migrations.AddField(
            model_name='prescription',
            name='description_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prescription',
            name='description_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prescription',
            name='description_3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prescription',
            name='description_4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prescription',
            name='description_5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_1',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_2',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_3',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_4',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_5',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='prescription',
            name='eat_time_1',
            field=models.CharField(choices=[('Before Eat', 'Before Eat'), ('After Eat', 'After Eat')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='eat_time_2',
            field=models.CharField(choices=[('Before Eat', 'Before Eat'), ('After Eat', 'After Eat')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='eat_time_3',
            field=models.CharField(choices=[('Before Eat', 'Before Eat'), ('After Eat', 'After Eat')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='eat_time_4',
            field=models.CharField(choices=[('Before Eat', 'Before Eat'), ('After Eat', 'After Eat')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='eat_time_5',
            field=models.CharField(choices=[('Before Eat', 'Before Eat'), ('After Eat', 'After Eat')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency_1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency_2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency_3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency_4',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency_5',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='test_name_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='test_name_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='test_name_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='test_name_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='test_name_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
