# Generated by Django 4.1.7 on 2023-04-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_user_patient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='email',
            new_name='user',
        ),
    ]
