# Generated by Django 4.1.7 on 2023-04-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
