# Generated by Django 4.2.1 on 2023-05-13 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0016_alter_donationrequest_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_required', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('age', models.PositiveIntegerField()),
                ('hospital', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('is_approved', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PANDING', 'PANDING'), ('REJECT', 'REJECT')], default='PENDING', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
