# Generated by Django 4.2.1 on 2023-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_alter_appointment_google_meet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='google_meet_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
