# Generated by Django 4.2.1 on 2023-05-30 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0014_rename_name_prescription_doctor_name_and_more'),
        ('adminView', '0002_diagnostic'),
        ('patient', '0026_alter_appointment_google_meet_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=250)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.BooleanField(default=False)),
                ('additional_tests', models.ManyToManyField(related_name='additional_orders', to='adminView.diagnostic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminView.diagnostic')),
            ],
        ),
    ]
