# Generated by Django 4.2.1 on 2023-05-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0028_diagnosticorder_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticorder',
            name='test',
        ),
    ]
