# Generated by Django 4.2.1 on 2023-05-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0029_remove_diagnosticorder_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticorder',
            old_name='patient',
            new_name='user',
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='patient_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='patient_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='patient_mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
