# Generated by Django 4.2.1 on 2023-05-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0030_rename_patient_diagnosticorder_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticorder',
            old_name='user',
            new_name='patient',
        ),
    ]
