# Generated by Django 4.2.1 on 2023-05-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0031_rename_user_diagnosticorder_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticorder',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
    ]
