# Generated by Django 3.2 on 2023-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic/Doctor'),
        ),
    ]
