# Generated by Django 4.2.1 on 2023-05-27 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0011_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(max_length=10)),
                ('patient_blood_pressure', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(max_length=254)),
                ('registration_number', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_phone', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('morning', models.BooleanField()),
                ('afternoon', models.BooleanField()),
                ('evening', models.BooleanField()),
                ('duration', models.CharField(max_length=50)),
                ('meal_time', models.CharField(max_length=10)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
    ]
