# Generated by Django 4.2.1 on 2023-05-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_prescription_test_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='eat_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='problem',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
