# Generated by Django 4.2.1 on 2023-06-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_rename_name_prescription_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
