# Generated by Django 4.2 on 2023-05-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_remove_donor_user_remove_receiver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='donor',
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='address',
            field=models.CharField(default='Nothing', max_length=40),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='email',
            field=models.EmailField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_by_donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodbank.blooddonate'),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
